### ISSUE TITLE
Need ur help

### ISSUE THREAD

**Issue by 90000988** [razorx89/roco-dataset#18]
Could you please lemme know how did you downloaded the data from PubMed. And why this url is not workinghttps://www.ncbi.nlm.nih.gov/pmc/utils/oa/oa.fcgi?tool=roco-fetch&email=johannes.rueckert@fh-dortmund.de&id=.
Thank you.

**Comment by saviola777** [comment]
Hello,

the URL is working, it just needs a PMCID, e.g.

`https://www.ncbi.nlm.nih.gov/pmc/utils/oa/oa.fcgi?tool=roco-fetch&email=your.email@example.com&id=PMC4608653`

It returns an XML response which includes the FTP link to the article, which we then use to download it.

If you are writing your own script to download articles from PMC, please make sure to use your own e-mail address in the link instead of mine.

For more information, please refer to the documentation:

- [Download through AWS](https://www.ncbi.nlm.nih.gov/pmc/tools/pmcaws/)
- [Download through FTP](https://www.ncbi.nlm.nih.gov/pmc/tools/ftp/)
- [OA Web Service API](https://www.ncbi.nlm.nih.gov/pmc/tools/oa-service/) to discover resources (e.g., new articles added since date X)

**Comment by 90000988** [comment]
Thank you for your response.
Bro Could you do me a favor? Please.
I am going to do a project related to medical domain, if you don't mind
guide me how to download these medical images, sem type, cuis, etc from
PubMed, it was my first project,i didn't have any idea,until u send those
urls, i really appreciate it. Please bro. Help me how to download these
data.
Thank you in advance.

**Comment by saviola777** [comment]
I'm not sure what exactly you are trying to do. If you just need the dataset, you can check out [ROCOv2](https://zenodo.org/records/8333645).

**Comment by 90000988** [comment]
Bro, I am going to do a project which is different from this, I need these
data from PubMed, could you please guide me how to search and get this data
set from PubMed please🙏.

**Comment by saviola777** [comment]
The only things you can get directly from PubMed are the articles, images, and image captions.

- first you download the archives from the FTP / AWS
- then you extract the images
- then you extract the captions for the images from the NXML file
- then you need to classify the images to keep only [non-compound radiological images](https://gitlab.com/saviola/rocov2-code/-/tree/main/roco-2018)
- then you need to clean the captions
- then you need to extract CUIs from the captions using something like [MedCAT](https://github.com/CogStack/MedCAT)
- then you need to filter CUIs otherwise you get lots of nonsense

Good luck.

**Comment by 90000988** [comment]
Thanks for the tip!

**Comment by 90000988** [comment]
Bro, thanks for your reply, could I ask one more thing, when I tried to
download the images from PubMed, articles are downloaded, it doesn't have
images. Could you guide me please.
Thanks in advance.

**Comment by saviola777** [comment]
I guess you are downloading the wrong archives.

> $ wget -r ftp://ftp.ncbi.nlm.nih.gov/pub/pmc/oa_package/96/5a/PMC1660580.tar.gz
> […]
> 2024-03-27 11:42:12 (1,20 MB/s) - ‘ftp.ncbi.nlm.nih.gov/pub/pmc/oa_package/96/5a/PMC1660580.tar.gz’ saved [701386]
> $ tar xvf ftp.ncbi.nlm.nih.gov/pub/pmc/oa_package/96/5a/PMC1660580.tar.gz                                                           
PMC1660580/
PMC1660580/1746-160X-2-40-6.jpg
PMC1660580/1746-160X-2-40-2.gif
PMC1660580/1746-160X-2-40-3.jpg
PMC1660580/1746-160X-2-40-6.gif
PMC1660580/1746-160X-2-40-8.jpg
PMC1660580/1746-160X-2-40-7.jpg
PMC1660580/1746-160X-2-40-8.gif
PMC1660580/1746-160X-2-40-4.gif
PMC1660580/1746-160X-2-40-4.jpg
PMC1660580/1746-160X-2-40-1.jpg
PMC1660580/1746-160X-2-40-3.gif
PMC1660580/1746-160X-2-40-5.gif
PMC1660580/1746-160X-2-40-5.jpg
PMC1660580/1746-160X-2-40-2.jpg
PMC1660580/1746-160X-2-40.pdf
PMC1660580/1746-160X-2-40-7.gif
PMC1660580/1746-160X-2-40-1.gif
PMC1660580/1746-160X-2-40.nxml

All images and nxml are there.
